### ISSUE TITLE
Unable to update firmware

### ISSUE THREAD

**Issue by Danbo0815** [pinguinpfleger/PrinCube-hack#1]
I tried to upload a firmware (tar created in Windows / cmd) using the web interface I get the error messages "Upgrade failed: err: 126" or "Upgrade failed: err: 127".
What could be the root cause for that problem?
Thanks!

**Comment by pinguinpfleger** [comment]
Hi,
I don't know, please ask the maintainers of the original source code.https://github.com/dukelec/mb

**Comment by martin-at-schorsch** [comment]
You mentioned windows cmd tar command.

I noticed that windows cmd tar command does not set execute bit on run.sh. This is casing the  error messages "Upgrade failed: err: 126" 
Use 7-zip to tar on windows, this works. 
![2021-02-09 22_01_57](https://user-images.githubusercontent.com/8039559/107428635-37da1a80-6b23-11eb-9422-57c6b85e64a3.png)
