### ISSUE TITLE
Merge with new firmware?

### ISSUE THREAD

**Issue by ilgrank** [pinguinpfleger/PrinCube-hack#4]
It seems the original author just updated both the app and the firmware with some **big** improvement
https://github.com/dukelec/mb/releases

**Comment by martin-at-schorsch** [comment]
Yes, and the mod does not work anymore, at least the GUI addon does not show.

**Comment by raenye** [comment]
The wifi client part works, and is completely separate from the shell part.
Should be split to two distinct updates IMHO.

**Comment by crowdstar5566** [comment]
Does the wifi client really still work?  I upload and get a "upgrade succeeded, reboot..." message but I don't see any changes.
Is there a login to ssh into the printer?  Thanks.

**Comment by pinguinpfleger** [comment]
I have just updated this hack.
